include: package:very_good_analysis/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-dynamic: true
  exclude:
    - "**.gr.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    public_member_api_docs: false
    always_use_package_imports: false
